#!name=LightRoom [ Premium ]

#!desc=By Biguudev ( Enjoy ! )

#!icon=https://raw.githubusercontent.com/deezertidal/private/main/icons/lightroom.png

#!tiktok/biguu.editz__




[MITM]

hostname = %APPEND% photos.adobe.io



[Script]

LightRoom=type=http-response,pattern=^https:\/\/photos\.adobe\.io\/v2\/accounts*,requires-body=1,script-path=https://raw.githubusercontent.com/litieyin/AD_VIP/main/Script/lightroom.js

